/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import googleMaps from "@amicaldo/strapi-google-maps/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import metajobStrapi from "metajob-strapi/strapi-admin";
import locationField from "strapi-location-field-plugin/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import reactIcons from "strapi-plugin-react-icons/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "google-maps": googleMaps,
    "color-picker": colorPicker,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "metajob-strapi": metajobStrapi,
    "location-field": locationField,
    "multi-select": multiSelect,
    "react-icons": reactIcons,
  },
});
